#!/bin/bash

# Make sure the user data directory is owned by the developer user
#if [ -d /home/developer/.IdeaIC2017.1 ]; then
#  sudo chown developer:developer /home/developer/.IdeaIC2017.1
#fi
exec /opt/android-studio/bin/studio.sh